### ISSUE TITLE
Tell User What to Do

### ISSUE THREAD

**Issue by bencevans** [lisezmoi/scri.ch#12] opened 2012-09-18 22:32 UTC
It would be good if there was something displaying when the user hits the site telling them to click and drag their mouse around the screen. When I first went onto the site I thought it hadn't finished loading or something so I hit refresh a few times, then looked at source to find out.

Ben.

**Comment by bpierre** [comment] 2012-09-19 13:13
This was discussed a lot during the design phase. I think a lot of people are leaving the website without trying to understand, thinking it does not load or something. The problem is that we really like the blank page.

Some solutions:
- Add a tooltip after a delay if the user has not clicked. But it’s not perfect, I think people will leave the website before the end of the delay. If the delay is too short, it is not a blank page anymore.
- Use the title or the favicon to display a hint.
- Keep it blank, and accept that some users will never see it.

**Comment by raphaelbastide** [comment] 2012-09-19 18:23
You are right Ben.

We found with @bpierre a fun way to inform users what to do.
http://jsbin.com/uniquv/6

Everything is in the page title. Once you come on the website it says that you can draw. Then when you begin to draw, the title react as a remote feedback.
What do you think?

**Comment by mauricesvay** [comment] 2012-09-19 18:52
How about a default sketch that acts like a tutorial?

http://scri.ch/cun

**Comment by bpierre** [comment] 2012-09-19 21:58
@mauricesvay I like the idea to use the tool itself. We are already doing this with the 404, which is a drawing like others (you can draw, save etc.) except for the title and the HTTP code: http://scri.ch/aaaaa.

But we want to keep the blank homepage. I know this is against all principles, but I want to keep it efficient for the “power user”. Even if the computer is not yours (no cookies), three simple steps are needed to make a drawing:
- Open http://scri.ch/
- Draw
- Save

**Comment by mauricesvay** [comment] 2012-09-19 22:04
Oh the 404 is really cool.

Changing the cursor to a pen maybe? Or show a short animation of a pen scribbling ?
Or go for skeuomorphism. Even if it's controversial, you could give the service a notebook look and get instant affordance.

**Comment by raphaelbastide** [comment] 2012-09-19 22:29
Scrich is based on a strict minimal design. We try to make it as simple as it can be, cross plateform and extendible.
- Cursor: Why not, but what about touch devices?
- Pen animation: Yes, in the page title just like this demo http://jsbin.com/uniquv/6
- Notebook look: Definitively not for me: perishable, not "Internet friendly", illustrative, will be a break for scri.ch future evolution (embeding, extension…). A blank page is so responsive :-)

**Comment by quentint** [comment] 2012-09-20 13:08
Interesting discussion!
I don't remember how I felt when I first landed on Scrich, I was probably a bit lost. But this only happens once, since you really "get it" quickly.

To me the title bar animation is the best because it's discreet and it doesn't add anything in the canvas (you could also animate the favicon) but that's probably also the problem.

I think you should try it and see if your user bounce rate changes, that'd be good metrics!

ps: Browser notifications could be cool be they require permissions...

**Comment by raphaelbastide** [comment] 2012-09-21 15:45
So… Should we go for http://jsbin.com/uniquv/6 ?
(I really like this fun and subtle way to solve the issue).

**Comment by quentint** [comment] 2012-09-21 15:49
Yup, I'd go for it!

**Comment by bpierre** [comment] 2012-09-21 16:02
:+1:

**Comment by nclm** [comment] 2012-10-01 18:55
Hello,
It may be somewhat too late, but I am not — as a user only — convinced about adding anything, whatever it is, to guide the first-time visitor. On the canvas itself, I think it's a no for everyone, but even in the < title > or in the favicon I would feel it as already too much.
Part of the brilliantness of scri.ch is in this absolute troubling minimalism when you first visit the page. The nothing is part of the experience. If you're curious, you try to click (or you display the source as mentioned before), you see what happens and you understand. And clearly the name itself is quite explicit to bring up drawing, that's already a guide.
I don't know if there's any statistics thingy running on scri.ch, but there's two things that would be interesting to see. The first is how many people leave the blank page without doing anything on their first visit ; They may not be as much. The second is in which ratio new visitors are landing : on a drawing / on the blank page ; I like to imagine that most new scri.ch users are discovering it thanks to someone sending them a drawing, but I may be wrong.
These two facts can be useful to see if it's really necessary to add a help, and break a little part of what makes scri.ch so rad, or no, and maybe loose some potential less curious users, but how many?
— Nicolas.

**Comment by raphaelbastide** [comment] 2013-01-15 23:17
Ok we are in a pre-test phase now.
Statistics are recorded to know a real user bounce (user don't draw and go).
Then we will try [this idea](http://jsbin.com/uniquv/6) for a while.
What we need now is a lot of users! You can talk and share around you :3

**Comment by bpierre** [comment] 2013-02-06 16:22
OK, the updated bounce rate is 31% since we started to include users who draw without saving. It was 51% on the same period before that (25 days). Not very relevant though, scri.ch did not receive a lot of traffic lately.

We pushed the test: an animated `Draw! ✎` in the `<title>`, which disappears completely after the first click.

Let’s see how this number will evolve!

![](http://f.cl.ly/items/3w1m2B0k0x1T1G3A1x2g/scrich-bounce-rate.png)

**Closed as completed** 2022-07-20 17:02 UTC
